import React from 'react';
import styled from 'styled-components';

const ASCII = styled.pre`
  color: ${props => props.theme.green};
  user-select: none;
`;

const MongoASCII = () => (
  <code><ASCII>{
`                                                                                                                                                                                                                                                          
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   :\`                                                                                                                               
                                                                                                  \`+/\`                                                                                                                              
                                                                                                  :+o/                                                                                                                              
                                                                                                \`/++oo/                                                                                                                             
                                                                                              \`-++++oso/\`                                                                                                                           
                                                                                            .:++++++osso+.                                                                                                                          
                                                                                          ./+oooo+++osssso-                                                                                                                         
                                                                                        ./+ooooooo++ossssso/.                                                                                                                       
                                                                                      ./+ooooooooo++ossssssso/.                                                                                                                     
                                                                                    ./+oooooooooooo+ossssssssso/.                                                                                                                   
                                                                                  \`:+ooooooooooooooooosssssssssso:\`                                                                                                                 
                                                                                 -+ooooooooooooooooooosssssssssssso:\`                                                                                                               
                                                                               \`:ooooooooooooooooooooossssssssssssss+-                                                                                                              
                                                                              -+oooooooooooooooooooooossssssssssssssso/\`                                                                                                            
                                                                            \`:oooooooooooooooooooooooossssssssssssssssso-                                                                                                           
                                                                           ./ooooooooooooooooooooooooosssssssssssssssssso/\`                                                                                                         
                                                                          .+oooooooooooooooooooooooooossssssssssssssssssss+.                                                                                                        
                                                                         :oooooooooooooooooooooooooooossssssssssssssssssssso:                                                                                                       
                                                                        :ooooooooooooooooooooooooooooosssssssssssssssssssssss/\`                                                                                                     
                                                                      \`/oooooooooooooooooooooooooooooossssssssssssssssssssssss+\`                                                                                                    
                                                                     \`/ooooooooooooooooooooooooooooooossssssssssssssssssssssssso.                                                                                                   
                                                                     /oooooooooooooooooooooooooooooooosssssssssssssssssssssssssso.                                                                                                  
                                                                    /ooooooooooooooooooooooooooooooooossssssssssssssssssssssssssso-                                                                                                 
                                                                   :oooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssso.                                                                                                
                                                                  -ooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssso.                                                                                               
                                                                 .oooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssso.                                                                                              
                                                                \`+oooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssso\`                                                                                             
                                                                /ooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssss/                                                                                             
                                                               -oooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssss:                                                                                            
                                                              \`ooooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssso-                                                                                           
                                                              :ooooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssso\`                                                                                          
                                                             \`oooooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssss/                                                                                          
                                                             /sooooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssss.                                                                                         
                                                            .oosoooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssss+\`                                                                                        
                                                            :sssoooooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssss:                                                                                        
                                                           \`ossssooooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssso\`                                                                                       
                                                           -osssssoooooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssss:                                                                                       
                                                           /sssssssooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssso\`                                                                                      
                                                           osssssssooooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssss-                                                                                      
                                                          .sssssssssoooooooooooooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssss/                                                                                      
                                                          :ssssssssssooooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssso\`                                                                                     
                                                          /sssssssssssoooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssso.                                                                                     
                                                         \`+sssssssssssoooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss-                                                                                     
                                                         \`ossssssssssssooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss:                                                                                     
                                                         \`ossssssssssssooooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss/                                                                                     
                                                         .osssssssssssssoooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss+                                                                                     
                                                         .ossssssssssssssooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss+                                                                                     
                                                         .ossssssssssssssooooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss+                                                                                     
                                                         .osssssssssssssssoooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss+                                                                                     
                                                         \`ossssssssssssssssooooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss/                                                                                     
                                                         \`osssssssssssssssssoooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss/                                                                                     
                                                         \`/sssssssssssssssssoooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss:                                                                                     
                                                          :sssssssssssssssssoooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssss.                                                                                     
                                                          .ssssssssssssssssssooooooooooooooooooooooooossssssssssssssssssssssssssssssssssssssso\`                                                                                     
                                                           ossssssssssssssssssoooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssss+                                                                                      
                                                           :sssssssssssssssssssooooooooooooooooooooooosssssssssssssssssssssssssssssssssssssss:                                                                                      
                                                           \`osssssssssssssssssssoooooooooooooooooooooosssssssssssssssssssssssssssssssssssssss\`                                                                                      
                                                            /sssssssssssssssssssoooooooooooooooooooooossssssssssssssssssssssssssssssssssssss/                                                                                       
                                                            .osssssssssssssssssssooooooooooooooooooooossssssssssssssssssssssssssssssssssssss.                                                                                       
                                                             :sssssssssssssssssssooooooooooooooooooooosssssssssssssssssssssssssssssssssssss/                                                                                        
                                                             \`+sssssssssssssssssssoooooooooooooooooooosssssssssssssssssssssssssssssssssssso.                                                                                        
                                                              .osssssssssssssssssssooooooooooooooooooossssssssssssssssssssssssssssssssssss:                                                                                         
                                                               :sssssssssssssssssssooooooooooooooooooosssssssssssssssssssssssssssssssssss+\`                                                                                         
                                                               \`/sssssssssssssssssssoooooooooooooooooosssssssssssssssssssssssssssssssssss.                                                                                          
                                                                \`+sssssssssssssssssssoooooooooooooooosssssssssssssssssssssssssssssssssss:                                                                                           
                                                                 \`+ssssssssssssssssssoooooooooooooooossssssssssssssssssssssssssssssssss:                                                                                            
                                                                  \`+ssssssssssssssssssooooooooooooooosssssssssssssssssssssssssssssssss/\`                                                                                            
                                                                   \`+sssssssssssssssssooooooooooooooossssssssssssssssssssssssssssssss+\`                                                                                             
                                                                    \`+sssssssssssssssssoooooooooooooosssssssssssssssssssssssssssssss/\`                                                                                              
                                                                     \`/sssssssssssssssssooooooooooooossssssssssssssssssssssssssssss/\`                                                                                               
                                                                       :ossssssssssssssssoooooooooooosssssssssssssssssssssssssssss/                                                                                                 
                                                                        -+sssssssssssssssoooooooooooossssssssssssssssssssssssssso-                                                                                                  
                                                                         \`/sssssssssssssssooooooooooosssssssssssssssssssssssssso.                                                                                                   
                                                                           :osssssssssssssooooooooooosssssssssssssssssssssssss/\`                                                                                                    
                                                                            .+sssssssssssssoooooooooossssssssssssssssssssssso-                                                                                                      
                                                                              :ossssssssssssoooooooo+ssssssssssssssssssssss+.                                                                                                       
                                                                               ./ossssssssssoooooooo/ossssssssssssssssssso-                                                                                                         
                                                                                 .+osssssssssooooooo/ossssssssssssssssso/\`                                                                                                          
                                                                                  \`-+ossssssssooooo+/+ssssssssssssssss/.                                                                                                            
                                                                                    \`-+osssssssoooo+//osssssssssssss+.                                                                                                              
                                                                                      \`:+osssssoooo////sssssssssss+.                                                                                                                
                                                                                        \`-+ossssoo+////+ssssssso/.                                                                                                                  
                                                                                           -/oosoo+///::+sssso:\`                                                                                                                    
                                                                                             .:ooo////:::://-\`                                                                                                                      
                                                                                               \`:////::::-\`                                                                                                                         
                                                                                                 ://::::-.                                                                                                                          
                                                                                                 \`//::::-                                                                                                                           
                                                                                                  -::::-.                                                                                                                           
                                                                                                  .::::-.                                                                                                                           
                                                                                                  \`:::--\`                                                                                                                           
                                                                                                   -:---\`                                                                                                                           
                                                                                                   -:--.\`                                                                                                                           
                                                                                                   .---.\`                                                                                                                           
                                                                                                   .--..\`                                                                                                                           
                                                                                                   .-...\`                                                                                                                           
                                                                                                   \`...\`\`                                                                                                                           
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    
                                                                                                                                                ................\`\`\`            ..............\`\`\`                                    
                                                                                                                                               \`..-------.....-------.\`       \`...-----....------.                                  
                                                                                                                                                   .::--        \`\`.-::--\`         -:::.      \`-:::-\`                                
                                                                                                                                                   .::--           \`.-::-.        -:::.       \`-:::.                                
                               \`          \`                    \`                        \`\`                   \`                     \`               \`-::-             .-::-.       -:::.        -::-\`                                
                  \`.-:/+s\`\`-/osss+-\` \`-/ossso:\`          \`-/+ossss+/.      \`.--:+o/\`.:+ssss/.          \`.:+oosso+:-.--/      \`-/+ossss+/.          \`-::-              -:::-\`      -:::.      \`.---\`                                 
                  .+shhhh+oo+++shhho+ooo+oshhhy.       \`/sy+-..-/shhyo-    .+syhhhsosoooshhhy/        -sys-.../yhhhysy+    \`/yyo-..-/ohhyo-        .:::-              .-:::.      -:::-.....--:-.\`                                  
                    \`ohhh:\`    \`+hhho.\`   \`:yhhs\`     -shh:      \`:yhhy-     \`:hhhs-\`   \`-yhhh.      :hhy.     .hhho.\`    -shh:      \`:yhhy:       .:::-              \`-:::.      -:::-......--:---.                                
                     /hhh       .yhh+       +hhy.    \`shhs\`        :hhhy\`     .yhh+       /hhh/      ohhy\`      shho      shhs\`        :hhhy\`      .:::-              \`-::-\`      -:::.       \`.-::--                               
                     /hhh       \`shh+       /hhy.    .hhho\`        \`yhhh\`     .yhho       :hhh/      +hhh/     .yhy-     .hhho\`        \`yhhh.      \`-::-              .:::-       -:::.         .::::.                              
                     /hhh       \`shh+       /hhy.    .yhhy.        \`shhh\`     .yhho\`      :hhh/      \`ohhho:--:syo-      \`hhhy.        \`shhy\`      .::--             .-::-\`       -:::.         \`-:::\`                  
                     /hhh       \`shh+       /hhy.    \`ohhh+        .yhh+      -hhho\`      :hhh/        -+yhso+/:.         ohhh+\`       .yhh+       .::--            .-:-.         -:::.         .::--               
                     +hhh\`      .yhho       +hhh-     .ohhh+.\`    .+hy+\`      -hhho\`      :hhh+       .+shs..\`\`\`\`\`        .ohhho.\`    \`ohy+\`       .:::-.\`       \`.---.\`          -:::-\`      \`.---.                      
                  ./oyhhho+-  -+ohhhyo/. \`/+yhhhs+/\`   \`/syhyo+//+ss+.      :+shhhho/.  :+yhhhyo+.    :yhhhhyyyssso+:.     \`:syhys+//+ss+.      \`.--:::::----.-----.\`         \`..--::::----.----.\`                    
                  .:------:.  -::----::\` \`---------      \`.-//+//-.\`        :::::::::.  ::::::::/\`     -ohsooossyyhhhy-      \`.-//+//-.\`        \`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`\`             \`\`\`\`\`\`\`                 
                                                                                                     .+yo-\`     \`./yhho                                                                                                             
                                                                                                    -yhy.          +hh:                                                                                                             
                                                                                                    :hhh/\`       \`-yy/                                                                                                              
                                                                                                     /yhhyo/::::+ss/.                                                                                                               
                                                                                                      \`-/osssso+:.                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                           

`
  }</ASCII></code>
);

export default MongoASCII;